name: Test Action
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci

      - name: Build action
        run: npm run build
      
      - name: Setup test project
        working-directory: ./test-project
        run: npm install
      
      - name: Run Jest tests
        run: npm test
      
      # Test the actual GitHub Action
      - name: Test action - should find errors and fail
        id: test-fail
        uses: ./
        continue-on-error: true
        with:
          working-directory: './test-project'
          fail-on-warnings: false
          fail-on-hints: false
      
      - name: Verify action found errors
        run: |
          echo "Action outcome: ${{ steps.test-fail.outcome }}"
          echo "Errors found: ${{ steps.test-fail.outputs.errors }}"
          echo "Warnings found: ${{ steps.test-fail.outputs.warnings }}"
          echo "Hints found: ${{ steps.test-fail.outputs.hints }}"
          
          if [ "${{ steps.test-fail.outcome }}" != "failure" ]; then
            echo "❌ Expected action to fail due to errors"
            exit 1
          fi
          
          if [ "${{ steps.test-fail.outputs.errors }}" -eq "0" ]; then
            echo "❌ Expected to find TypeScript errors"
            exit 1
          fi
          
          echo "✅ Action correctly failed with ${{ steps.test-fail.outputs.errors }} errors"
      
      - name: Test action - should fail on warnings when enabled
        id: test-warnings
        uses: ./
        continue-on-error: true
        with:
          working-directory: './test-project'
          fail-on-warnings: true
          fail-on-hints: false
      
      - name: Verify action failed on warnings
        run: |
          if [ "${{ steps.test-warnings.outcome }}" != "failure" ]; then
            echo "❌ Expected action to fail on warnings"
            exit 1
          fi
          echo "✅ Action correctly failed when fail-on-warnings enabled"
